## Configuration blocks

config_blocks:
  only_tags: &only_tags
    filters:
      branches:
        ignore: /.*/
      tags:
        only: /^v[0-9]+(\.[0-9]+)*$/

version: 2.1

jobs:
  update:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run: 
          command: |
            cd openapi
            curl --request PUT --url https://dash.readme.com/api/v1/api-specification/6290d77179fba9009e611e37 --header 'Accept: application/json' --header 'Authorization: Basic ${README_KEY}' --header 'Content-Type: multipart/form-data' --form spec=@spec31.yaml

workflows:
  update-reference:
    jobs:
      - update:
          <<: *only_tags

